---
- name: CVP Image Update
  hosts: cv_server
  gather_facts: no
  vars:

  tasks:
    - name: "Gather CVP image information from {{inventory_hostname}}"
      arista.cvp.cv_image_v3:
         mode: image
         action: get
      register: image_facts

    - name: "Current images on {{inventory_hostname}}"
      debug:
        msg: "{{image_facts}}"

    - name: "Add new EOS lab image {{inventory_hostname}}"
      vars:
        ansible_command_timeout: 1200
        ansible_connect_timeout: 1200
      arista.cvp.cv_image_v3:
        mode: image
        action: add
        image: /home/colin/image_testing/images/vEOS-lab-4.27.3.1F.swi

    - name: "Add new TerminAttr lab image on {{inventory_hostname}}"
      vars:
        ansible_command_timeout: 1200
        ansible_connect_timeout: 600
      arista.cvp.cv_image_v3:
        mode: image
        action: add
        image: /home/colin/image_testing/images/TerminAttr-1.19.2-1.swix

    - name: "Create an image bundle on {{inventory_hostname}}"
      arista.cvp.cv_image_v3:
        mode: bundle
        action: add
        bundle_name: spine_bundle
        image_list:
           - vEOS-lab-4.27.3.1F.swi
           - TerminAttr-1.19.2-1.swix

    - name: "Gather CVP image bundle info from {{inventory_hostname}}"
      arista.cvp.cv_image_v3:
        mode: bundle
        action: get
      register: cv_facts

    - name: "Print out bundle information from {{inventory_hostname}}"
      debug:
        msg: "{{cv_facts}}"